//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMentorApi.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechMentorApi.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} value is invalid. Please provide a year between 1988 and the current year inclusive..
        /// </summary>
        internal static string InvalidYearInRangeFormat {
            get {
                return ResourceManager.GetString("InvalidYearInRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Code of Conduct to make your profile publicly available..
        /// </summary>
        internal static string NoCocConsent_Message {
            get {
                return ResourceManager.GetString("NoCocConsent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Terms and Conditions as well as the Code of Conduct to make your profile publicly available..
        /// </summary>
        internal static string NoConsent_Message {
            get {
                return ResourceManager.GetString("NoConsent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} value must not contain / or \..
        /// </summary>
        internal static string NoSlashAttribute_MessageFormat {
            get {
                return ResourceManager.GetString("NoSlashAttribute_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Terms and Conditions to make your profile publicly available..
        /// </summary>
        internal static string NoTacConsent_Message {
            get {
                return ResourceManager.GetString("NoTacConsent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested item was not found..
        /// </summary>
        internal static string NotFoundException_Message {
            get {
                return ResourceManager.GetString("NotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be true..
        /// </summary>
        internal static string RequireBooleanAttribute_Message {
            get {
                return ResourceManager.GetString("RequireBooleanAttribute_Message", resourceCulture);
            }
        }
    }
}
